"""Small supervised dataset used to train Intelispark's local intent model.

This is intentionally domain-specific: Kenyan commerce, electronics and WhatsApp sales.
The dataset is version-controlled so it can grow as real conversations are collected.
"""

TRAINING_EXAMPLES = [
    ("hi", "greeting"), ("hello", "greeting"), ("habari", "greeting"),
    ("mambo", "greeting"), ("good morning", "greeting"), ("hey there", "greeting"),
    ("how much is the phone", "price"), ("bei ya samsung", "price"),
    ("what is the price", "price"), ("how much does it cost", "price"),
    ("hii ni ngapi", "price"), ("is there a discount", "price"),
    ("do you have this phone", "availability"), ("is it in stock", "availability"),
    ("iko stock", "availability"), ("mna iphone 13", "availability"),
    ("is the samsung available", "availability"), ("do you still have it", "availability"),
    ("i want to buy it", "purchase"), ("i will take the phone", "purchase"),
    ("nataka kununua", "purchase"), ("place an order", "purchase"),
    ("how can i order", "purchase"), ("send me one", "purchase"),
    ("which phone has the best camera", "recommendation"),
    ("recommend a good samsung", "recommendation"), ("what do you recommend", "recommendation"),
    ("which one is better", "recommendation"), ("help me choose a phone", "recommendation"),
    ("best phone under 30000", "recommendation"),
    ("compare iphone and samsung", "comparison"), ("compare these phones", "comparison"),
    ("which is better between a15 and redmi", "comparison"),
    ("difference between these two", "comparison"), ("compare the cameras", "comparison"),
    ("can i pay in installments", "installment"), ("do you offer lipa polepole", "installment"),
    ("can i pay monthly", "installment"), ("is installment available", "installment"),
    ("i want a phone on installments", "installment"),
    ("where are you located", "location"), ("where is your shop", "location"),
    ("shop location", "location"), ("mko wapi", "location"),
    ("where can i collect it", "location"),
    ("can you deliver", "delivery"), ("do you deliver", "delivery"),
    ("delivery to kisumu", "delivery"), ("how much is delivery", "delivery"),
    ("can you send it to me", "delivery"),
    ("book an appointment", "appointment"), ("can i visit the shop", "appointment"),
    ("i want to come tomorrow", "appointment"),
    ("thank you", "thanks"), ("asante", "thanks"), ("thanks for your help", "thanks"),
    ("hi there", "greeting"), ("hey", "greeting"), ("niaje", "greeting"), ("sasa", "greeting"),
    ("good afternoon", "greeting"), ("good evening", "greeting"), ("morning", "greeting"),
    ("hello there", "greeting"), ("habari ya leo", "greeting"),
    ("how much is this", "price"), ("what's the price", "price"), ("how much", "price"),
    ("bei ni gani", "price"), ("bei yake ni ngapi", "price"), ("ni pesa ngapi", "price"),
    ("is this available", "availability"), ("is this still available", "availability"),
    ("do you have one", "availability"), ("mnayo", "availability"), ("iko available", "availability"),
    ("bado iko", "availability"), ("bado mnayo", "availability"),
    ("i'll take it", "purchase"), ("i want this one", "purchase"), ("i need this one", "purchase"),
    ("i'll buy it", "purchase"), ("nipe moja", "purchase"), ("nataka hii", "purchase"),
    ("nitataka moja", "purchase"), ("naweza kuagiza", "purchase"), ("order this for me", "purchase"),
    ("which one should i get", "recommendation"), ("help me find a phone", "recommendation"),
    ("suggest a phone", "recommendation"), ("suggest one", "recommendation"),
    ("phone ya camera nzuri", "recommendation"), ("simu ya camera nzuri", "recommendation"),
    ("simu nzuri chini ya 30000", "recommendation"), ("nishauri simu", "recommendation"),
    ("which is the better option", "comparison"), ("compare the two", "comparison"),
    ("difference between them", "comparison"), ("hii na hii ipi ni better", "comparison"),
    ("can i pay by installment", "installment"), ("lipa polepole", "installment"),
    ("mna installment", "installment"), ("do you have payment plans", "installment"),
    ("where is the shop located", "location"), ("location please", "location"),
    ("shop iko wapi", "location"), ("mko location gani", "location"), ("nitaipata wapi", "location"),
    ("can you ship", "delivery"), ("do you ship", "delivery"), ("send it to me", "delivery"),
    ("deliver to me", "delivery"), ("mna delivery", "delivery"), ("delivery mnafanya", "delivery"),
    ("can i pick it up", "location"), ("where do i collect", "location"),
    ("thank you so much", "thanks"), ("asante sana", "thanks"), ("shukran", "thanks"),
    ("i have a question", "general"), ("tell me more", "general"),
    ("i need help", "general"), ("what do you sell", "general"),
    ("what are your opening hours", "business_info"), ("when are you open", "business_info"),
    ("are you open today", "business_info"), ("what time do you close", "business_info"),
    ("what is your warranty", "business_info"), ("do you offer warranty", "business_info"),
    ("what is your return policy", "business_info"), ("can i return a phone", "business_info"),
    ("what payment methods do you accept", "business_info"), ("how can i pay", "business_info"),
    ("do you accept mpesa", "business_info"), ("do you take cash", "business_info"),
    ("tell me about the shop", "business_info"), ("how can i contact the shop", "business_info"),
    ("what is your phone number", "business_info"),
]
